ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hobbies text[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS zodiac text DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mbti text DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text DEFAULT '';
